<?php

/** 
 * @file
 * Learning Form API
 */

/**
 * Implements hook_menu
 */
function my_module1_menu() {
    $items["learn/form-api"] = array(
        'title' => 'First form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('first_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        
    );
    return $items;
}

/**
 * Define form
 */
function first_form() {
    $form['name'] = array(
        '#title' => t('Your name'),
        '#type' => 'textfield',
        '#description' => t('Please enter your name'),
    );
    
    $form['soname'] = array(
        '#title' => t('Your last name'),
        '#type' => 'textfield',
        '#description' => t('Please enter your last name.'),
    );
    
     $form['age'] = array(
        '#title' => t('Your age'),
        '#type' => 'textfield',
        '#description' => t('Please enter your age.'),
    );
     
     $form['title'] = array (
         '#title' => t('Title of the massage'),
         '#type' => 'textfield',
         '#description' => t('Plese enrer your title of massage'),
     );
     
     $form['text'] = array(
         '#title' => t('Your massage'),
         '#type' => 'textfield',
         '#description' => t('Please enter your massage'),
     );
   
    $form['email'] = array(
        '#title' => t('E-mail'),
        '#type' => 'textfield',
        '#description' => t('Please enter your E-mail adress.'),
    );
  
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('send'),
    );
    
    $form['#validate'][] = 'my_valid_function';
    $form['#submit'][] = 'my_submit_function';
    return $form;
}

    /**
     * Validation form
     */
    function first_form_validate($form, &$form_state) {
        if(!preg_match("'^([aA-zZ0-9\.-])*@(aA-zZ0-9])*.([aA-zZ0-9\.-])*$'",
                $form_state['values']['email'])){
            form_set_error("email", $form_state['values']['email'] . " is not valid email adress. ");
    }
    }
    /**
     * my_valid_function
     * @param array $form
     * @param array $form_state
     */
    function my_valid_function($form, &$form_state) {
        if(!preg_match("'^[A-Z]+([a-z])*$'", $form_state['values']['name'])){
            form_set_error("name", $form_state['values']['name']. " is not valid name. ");
        }
    }
     /**
     *  my_submit_function
     * @param array $form
     * @param array $form_state
     */
    function my_submit_function($form, &$form_state) { 
        $theme = "Form submit";
        $mail = "example@mail.test";
        $message = t('Form sender', array($form_state['values']['name']),
                                    array($form_state['values']['soname']),
                                    array($form_state['values']['age']),
                                    array($form_state['values']['title']),
                                    array($form_state['values']['text']),
                                    array($form_state['values']['email']));
        drupal_mail('system','mail','mamaev_andrei@mail.ru',language_default(),
                array('message' => $message)
            );
        dsm($form); 
        dsm($form_state);
        drupal_set_message(t(" Thanks, your form is submit. "));
    }